apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    release: "v0.1.0"
    app: "aegir"
  name: aegir
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: "aegir"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aegir
        release: "v0.1.0"
    spec:
      containers:
      - image: __REPO_IMAGE_TAG__
        imagePullPolicy: Always
        name: aegir
        args:
        - server
        - --rules-file
        - /etc/aegir/rules.yaml
        - --tls-cert-file
        - /tls/aegir-cert.crt
        - --tls-key-file
        - /tls/aegir-key.crt
        env:
          - name: SKIP_NAMESPACES
            value: "istio-system,kube-system"
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: https
            scheme: HTTPS
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - name: aegir-rules
          mountPath: /etc/aegir
        - name: aegir-tls
          mountPath: /tls
      volumes:
      - name: aegir-rules
        configMap:
          name: aegir-rules
          items:
          - path: rules.yaml
            key: rules.yaml
      - name: aegir-tls
        secret:
          secretName: aegir-tls
          items:
          - path: aegir-cert.crt
            key: tls.crt
          - path: aegir-key.crt
            key: tls.key

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aegir
  name: aegir
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: aegir
  sessionAffinity: None
  type: ClusterIP
