apiVersion: v1
kind: Service
metadata:
  labels:
    app: aegir
  name: aegir
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: aegir
  sessionAffinity: None
  type: ClusterIP
